package com.aoai.autobahn

data class LanguageOption(
    val code: String,
    val label: String
)

object LanguageOptions {
    val options = listOf(
        LanguageOption("auto", "Detect language"),
        LanguageOption("ko", "Korean"),
        LanguageOption("en", "English"),
        LanguageOption("ja", "Japanese"),
        LanguageOption("zh-CN", "Chinese (Simplified)"),
        LanguageOption("zh-TW", "Chinese (Traditional)"),
        LanguageOption("ab", "Abkhazian"),
        LanguageOption("ace", "Acehnese"),
        LanguageOption("ach", "Acoli"),
        LanguageOption("aa", "Afar"),
        LanguageOption("af", "Afrikaans"),
        LanguageOption("ak", "Akan"),
        LanguageOption("sq", "Albanian"),
        LanguageOption("alz", "Alur"),
        LanguageOption("am", "Amharic"),
        LanguageOption("ar", "Arabic"),
        LanguageOption("hy", "Armenian"),
        LanguageOption("as", "Assamese"),
        LanguageOption("av", "Avaric"),
        LanguageOption("awa", "Awadhi"),
        LanguageOption("ay", "Aymara"),
        LanguageOption("az", "Azerbaijani"),
        LanguageOption("ban", "Balinese"),
        LanguageOption("bal", "Baluchi"),
        LanguageOption("bm", "Bambara"),
        LanguageOption("bn", "Bangla"),
        LanguageOption("bci", "Baoulé"),
        LanguageOption("ba", "Bashkir"),
        LanguageOption("eu", "Basque"),
        LanguageOption("btx", "Batak Karo"),
        LanguageOption("bts", "Batak Simalungun"),
        LanguageOption("bbc", "Batak Toba"),
        LanguageOption("be", "Belarusian"),
        LanguageOption("bem", "Bemba"),
        LanguageOption("bew", "Betawi"),
        LanguageOption("bho", "Bhojpuri"),
        LanguageOption("bik", "Bikol"),
        LanguageOption("bs", "Bosnian"),
        LanguageOption("br", "Breton"),
        LanguageOption("bg", "Bulgarian"),
        LanguageOption("bua", "Buriat"),
        LanguageOption("my", "Burmese"),
        LanguageOption("yue", "Cantonese"),
        LanguageOption("ca", "Catalan"),
        LanguageOption("ceb", "Cebuano"),
        LanguageOption("ckb", "Central Kurdish"),
        LanguageOption("ch", "Chamorro"),
        LanguageOption("ce", "Chechen"),
        LanguageOption("cgg", "Chiga"),
        LanguageOption("chk", "Chuukese"),
        LanguageOption("cv", "Chuvash"),
        LanguageOption("co", "Corsican"),
        LanguageOption("crh", "Crimean Tatar"),
        LanguageOption("hr", "Croatian"),
        LanguageOption("cs", "Czech"),
        LanguageOption("da", "Danish"),
        LanguageOption("fa-AF", "Dari"),
        LanguageOption("din", "Dinka"),
        LanguageOption("dv", "Divehi"),
        LanguageOption("doi", "Dogri"),
        LanguageOption("dov", "Dombe"),
        LanguageOption("nl", "Dutch"),
        LanguageOption("dyu", "Dyula"),
        LanguageOption("dz", "Dzongkha"),
        LanguageOption("eo", "Esperanto"),
        LanguageOption("et", "Estonian"),
        LanguageOption("ee", "Ewe"),
        LanguageOption("fo", "Faroese"),
        LanguageOption("fj", "Fijian"),
        LanguageOption("fil", "Filipino"),
        LanguageOption("fi", "Finnish"),
        LanguageOption("fon", "Fon"),
        LanguageOption("fr", "French"),
        LanguageOption("fur", "Friulian"),
        LanguageOption("ff", "Fulani"),
        LanguageOption("gaa", "Ga"),
        LanguageOption("gl", "Galician"),
        LanguageOption("lg", "Ganda"),
        LanguageOption("ka", "Georgian"),
        LanguageOption("de", "German"),
        LanguageOption("el", "Greek"),
        LanguageOption("gn", "Guarani"),
        LanguageOption("gu", "Gujarati"),
        LanguageOption("ht", "Haitian Creole"),
        LanguageOption("cnh", "Hakha Chin"),
        LanguageOption("ha", "Hausa"),
        LanguageOption("haw", "Hawaiian"),
        LanguageOption("he", "Hebrew"),
        LanguageOption("hil", "Hiligaynon"),
        LanguageOption("hi", "Hindi"),
        LanguageOption("hmn", "Hmong"),
        LanguageOption("hu", "Hungarian"),
        LanguageOption("hrx", "Hunsrik"),
        LanguageOption("iba", "Iban"),
        LanguageOption("is", "Icelandic"),
        LanguageOption("ig", "Igbo"),
        LanguageOption("ilo", "Iloko"),
        LanguageOption("id", "Indonesian"),
        LanguageOption("ga", "Irish"),
        LanguageOption("it", "Italian"),
        LanguageOption("jam", "Jamaican Patois"),
        LanguageOption("jv", "Javanese"),
        LanguageOption("kac", "Jingpo"),
        LanguageOption("kl", "Kalaallisut"),
        LanguageOption("kn", "Kannada"),
        LanguageOption("kr", "Kanuri"),
        LanguageOption("kk", "Kazakh"),
        LanguageOption("kha", "Khasi"),
        LanguageOption("km", "Khmer"),
        LanguageOption("rw", "Kinyarwanda"),
        LanguageOption("ktu", "Kituba"),
        LanguageOption("kok", "Kokborok"),
        LanguageOption("kv", "Komi"),
        LanguageOption("kg", "Kongo"),
        LanguageOption("gom", "Konkani"),
        LanguageOption("kri", "Krio"),
        LanguageOption("ku", "Kurdish"),
        LanguageOption("ky", "Kyrgyz"),
        LanguageOption("lo", "Lao"),
        LanguageOption("ltg", "Latgalian"),
        LanguageOption("la", "Latin"),
        LanguageOption("lv", "Latvian"),
        LanguageOption("lij", "Ligurian"),
        LanguageOption("li", "Limburgish"),
        LanguageOption("ln", "Lingala"),
        LanguageOption("lt", "Lithuanian"),
        LanguageOption("lmo", "Lombard"),
        LanguageOption("luo", "Luo"),
        LanguageOption("lb", "Luxembourgish"),
        LanguageOption("mk", "Macedonian"),
        LanguageOption("mad", "Madurese"),
        LanguageOption("mai", "Maithili"),
        LanguageOption("mak", "Makasar"),
        LanguageOption("mg", "Malagasy"),
        LanguageOption("ms", "Malay"),
        LanguageOption("ms-Arab", "Malay (Arabic)"),
        LanguageOption("ml", "Malayalam"),
        LanguageOption("mt", "Maltese"),
        LanguageOption("mam", "Mam"),
        LanguageOption("mni-Mtei", "Manipuri (Meitei Mayek)"),
        LanguageOption("gv", "Manx"),
        LanguageOption("mi", "Māori"),
        LanguageOption("mr", "Marathi"),
        LanguageOption("mh", "Marshallese"),
        LanguageOption("mwr", "Marwari"),
        LanguageOption("mhr", "Meadow Mari"),
        LanguageOption("min", "Minangkabau"),
        LanguageOption("lus", "Mizo"),
        LanguageOption("mn", "Mongolian"),
        LanguageOption("mfe", "Morisyen"),
        LanguageOption("nhe", "Nahuatl (Eastern Huasteca)"),
        LanguageOption("ndc", "Ndau"),
        LanguageOption("new", "Nepalbhasa (Newari)"),
        LanguageOption("ne", "Nepali"),
        LanguageOption("nqo", "NKo"),
        LanguageOption("se", "Northern Sami"),
        LanguageOption("nso", "Northern Sotho"),
        LanguageOption("no", "Norwegian"),
        LanguageOption("nus", "Nuer"),
        LanguageOption("ny", "Nyanja"),
        LanguageOption("oc", "Occitan"),
        LanguageOption("or", "Odia"),
        LanguageOption("om", "Oromo"),
        LanguageOption("os", "Ossetic"),
        LanguageOption("pam", "Pampanga"),
        LanguageOption("pag", "Pangasinan"),
        LanguageOption("pap", "Papiamento"),
        LanguageOption("ps", "Pashto"),
        LanguageOption("fa", "Persian"),
        LanguageOption("pl", "Polish"),
        LanguageOption("pt", "Portuguese"),
        LanguageOption("pt-PT", "Portuguese (Portugal)"),
        LanguageOption("pa", "Punjabi"),
        LanguageOption("pa-Arab", "Punjabi (Arabic)"),
        LanguageOption("kek", "Q'eqchi'"),
        LanguageOption("qu", "Quechua"),
        LanguageOption("ro", "Romanian"),
        LanguageOption("rom", "Romany"),
        LanguageOption("rn", "Rundi"),
        LanguageOption("ru", "Russian"),
        LanguageOption("sm", "Samoan"),
        LanguageOption("sg", "Sango"),
        LanguageOption("sa", "Sanskrit"),
        LanguageOption("sat-Latn", "Santali (Latin)"),
        LanguageOption("gd", "Scottish Gaelic"),
        LanguageOption("sr", "Serbian"),
        LanguageOption("crs", "Seselwa Creole French"),
        LanguageOption("shn", "Shan"),
        LanguageOption("sn", "Shona"),
        LanguageOption("scn", "Sicilian"),
        LanguageOption("szl", "Silesian"),
        LanguageOption("sd", "Sindhi"),
        LanguageOption("si", "Sinhala"),
        LanguageOption("sk", "Slovak"),
        LanguageOption("sl", "Slovenian"),
        LanguageOption("so", "Somali"),
        LanguageOption("nr", "South Ndebele"),
        LanguageOption("st", "Southern Sotho"),
        LanguageOption("es", "Spanish"),
        LanguageOption("su", "Sundanese"),
        LanguageOption("sus", "Susu"),
        LanguageOption("sw", "Swahili"),
        LanguageOption("ss", "Swati"),
        LanguageOption("sv", "Swedish"),
        LanguageOption("ty", "Tahitian"),
        LanguageOption("tg", "Tajik"),
        LanguageOption("zgh", "Tamazight"),
        LanguageOption("tzm", "Tamazight (Tifinagh)"),
        LanguageOption("ta", "Tamil"),
        LanguageOption("tt", "Tatar"),
        LanguageOption("te", "Telugu"),
        LanguageOption("tet", "Tetum"),
        LanguageOption("th", "Thai"),
        LanguageOption("bo", "Tibetan"),
        LanguageOption("ti", "Tigrinya"),
        LanguageOption("tiv", "Tiv"),
        LanguageOption("tpi", "Tok Pisin"),
        LanguageOption("to", "Tongan"),
        LanguageOption("ts", "Tsonga"),
        LanguageOption("tn", "Tswana"),
        LanguageOption("tcy", "Tulu"),
        LanguageOption("tum", "Tumbuka"),
        LanguageOption("tr", "Turkish"),
        LanguageOption("tk", "Turkmen"),
        LanguageOption("tyv", "Tuvinian"),
        LanguageOption("udm", "Udmurt"),
        LanguageOption("uk", "Ukrainian"),
        LanguageOption("ur", "Urdu"),
        LanguageOption("ug", "Uyghur"),
        LanguageOption("uz", "Uzbek"),
        LanguageOption("ve", "Venda"),
        LanguageOption("vec", "Venetian"),
        LanguageOption("vi", "Vietnamese"),
        LanguageOption("war", "Waray"),
        LanguageOption("cy", "Welsh"),
        LanguageOption("fy", "Western Frisian"),
        LanguageOption("wo", "Wolof"),
        LanguageOption("xh", "Xhosa"),
        LanguageOption("sah", "Yakut"),
        LanguageOption("yi", "Yiddish"),
        LanguageOption("yo", "Yoruba"),
        LanguageOption("yua", "Yucatec Maya"),
        LanguageOption("zap", "Zapotec"),
        LanguageOption("zu", "Zulu")
    )
}
